language: node_js
node_js: "node"

before_script:
  - npm install @qooxdoo/compiler 
    if: branch = master

script:
  - npx qx compile --target=build -v
    if: branch = master
  

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: compiled/build
  on:
    branch: master
