language: node_js
node_js: "node"

before_script:
  - npm install qxcompiler 

script:
  - node_modules/qxcompiler/qx compile --target=build -v
  

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: compiled/build
  on:
    branch: master
